# This is a basic workflow to help you get started with Actions
name: build docker image

# Controls when the action will run.
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Scenario tags'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./config
          file: ./config/Dockerfile.nvim
          # 所需要的体系结构，可以在 Available platforms 步骤中获取所有的可用架构
          # platforms: linux/amd64,linux/arm64/v8
          platforms: linux/amd64,linux/arm64/v7
          # 镜像推送时间
          push: ${{ github.event_name != 'pull_request' }}
          # 给清单打上多个标签
          tags: |
            double12gzh/neovim:${{ steps.date.outputs.today }}
            double12gzh/neovim:latest
